# Generated by Django 3.1.2 on 2021-02-28 08:43

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=20)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='PosCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(blank=True, default='Shop Name', max_length=255, null=True)),
                ('address', models.CharField(blank=True, default='Bhopal, India', max_length=100, null=True)),
                ('country_located', models.CharField(blank=True, default='India', max_length=20, null=True)),
                ('email', models.EmailField(blank=True, default='admin@site.com', max_length=254, null=True)),
                ('phone_number', models.IntegerField(blank=True, default='1111111111', null=True)),
                ('whatsapp_number', models.IntegerField(blank=True, default='1111111111', null=True)),
                ('currency', models.CharField(blank=True, choices=[('₹', '₹'), ('Rs', 'Rs'), ('$', '$')], default='₹', max_length=5, null=True)),
                ('receipt_message', models.CharField(blank=True, default='Thank you for shopping', max_length=100, null=True)),
                ('receipt_tnc', ckeditor.fields.RichTextField(blank=True, default='<li>No Return on goods sold</li>', null=True)),
            ],
            options={
                'verbose_name': 'Site Configuration',
            },
        ),
    ]
