# Generated by Django 3.1.2 on 2023-03-29 16:08

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20230222_2201'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(blank=True, default='Shop Name', max_length=255, null=True)),
                ('tagline', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('address', models.CharField(blank=True, default='Bhopal, India', max_length=100, null=True)),
                ('country_located', models.CharField(blank=True, default='India', max_length=20, null=True)),
                ('email', models.EmailField(blank=True, default='admin@site.com', max_length=254, null=True)),
                ('phone_number', models.IntegerField(blank=True, default='1111111111', null=True)),
                ('whatsapp_number', models.IntegerField(blank=True, default='1111111111', null=True)),
                ('about_us', ckeditor.fields.RichTextField(blank=True, default='Welcome to our website.', null=True)),
                ('site_logo', models.ImageField(blank=True, default='images/default_shop_logo.jpg', null=True, upload_to='images/site_logo')),
                ('homepage_image', models.ImageField(blank=True, default='images/default_shop_logo.jpg', null=True, upload_to='images/homeepage_image')),
                ('instagram', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Website Configuration',
            },
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='youtube',
        ),
    ]
