# Generated by Django 3.1.2 on 2023-03-29 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20230329_1608'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Website',
            new_name='StoreSettings',
        ),
    ]
