# Generated by Django 3.1.2 on 2023-04-04 22:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_storesettings_about_us'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='about_us',
            field=ckeditor.fields.RichTextField(blank=True, default='Welcome to our website.', null=True),
        ),
    ]
