# Generated by Django 3.1.2 on 2023-04-04 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_storesettings_about_us'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storesettings',
            old_name='about_us',
            new_name='site_about_us',
        ),
    ]
