# Generated by Django 3.1.2 on 2023-06-21 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_storesettings_contact_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='menu_maker',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
