# Generated by Django 3.1.2 on 2022-04-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20220226_2334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariation',
            name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
