# Generated by Django 3.1.2 on 2023-02-03 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_product_min_mrp'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='min_mrp_image',
            field=models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='images/'),
        ),
    ]
