# Generated by Django 3.1.2 on 2020-10-17 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testproduct',
            name='variation',
        ),
        migrations.AddField(
            model_name='testproductvariations',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='testing.testproduct'),
        ),
    ]
