# Generated by Django 3.1.2 on 2020-10-17 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0003_testproductvariations_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='testproduct',
            name='main_variation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='testing.testproductvariations'),
        ),
    ]
