# Generated by Django 3.1.2 on 2023-02-18 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='shop_logo',
            field=models.ImageField(blank=True, default='images/default_shop_logo.jpg', null=True, upload_to='images/'),
        ),
    ]
