# Generated by Django 3.1.2 on 2021-09-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='shop_logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
