# Generated by Django 3.1.2 on 2023-02-24 00:41

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebUrls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='about_us',
            field=ckeditor.fields.RichTextField(blank=True, default='Welcome to our website.', null=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='shop_logo',
            field=models.ImageField(blank=True, default='images/default_shop_logo.jpg', null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='youtube',
            field=models.URLField(blank=True, null=True),
        ),
    ]
