# Generated by Django 3.1.2 on 2021-02-16 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_delete_poscustomer'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
