# Generated by Django 3.1.2 on 2023-02-21 18:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20230221_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='about_us',
            field=ckeditor.fields.RichTextField(blank=True, default='Welcome to our website.', null=True),
        ),
    ]
