# Generated by Django 3.1.2 on 2023-02-22 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_weburls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='youtube',
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='weburls',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.weburls'),
        ),
    ]
