# Generated by Django 3.1.2 on 2021-09-14 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210914_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='shop_logo',
            field=models.ImageField(default='images/default_logo.png', upload_to='images/'),
        ),
    ]
