# Generated by Django 3.1.2 on 2023-02-22 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20230222_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='weburls',
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='youtube',
            field=models.URLField(blank=True, null=True),
        ),
    ]
