# Generated by Django 3.1.2 on 2021-09-14 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210914_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='shop_logo',
            field=models.ImageField(default='images/IMG_0207.JPG', upload_to='images/'),
        ),
    ]
