# Generated by Django 3.1.2 on 2021-09-17 18:56

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210915_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='shop_logo',
            field=models.ImageField(blank=True, default='images/IMG_0207.JPG', null=True, upload_to='images/', validators=[accounts.models.clean_image]),
        ),
    ]
