# Generated by Django 3.1.2 on 2021-09-23 20:47

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210917_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='shop_logo',
            field=models.ImageField(blank=True, default='images/default_logo.png', null=True, upload_to='images/', validators=[accounts.models.clean_image]),
        ),
    ]
