# Generated by Django 3.1.2 on 2020-12-23 22:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_order', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('payment_mode', models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Paytm', 'Paytm'), ('UPI', 'UPI'), ('Other', 'Other')], default='Cash', max_length=10, null=True)),
                ('cart_revenue', models.FloatField(blank=True, null=True)),
                ('cart_profit', models.FloatField(blank=True, null=True)),
                ('cart_cost', models.FloatField(blank=True, null=True)),
                ('cart_mrp', models.FloatField(blank=True, null=True)),
                ('cart_quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('complete', models.BooleanField(default=False, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategories',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'ProductCategories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_code', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('cost', models.FloatField()),
                ('mrp', models.FloatField()),
                ('discount_price', models.FloatField(blank=True, null=True)),
                ('discount_percentage', models.FloatField(blank=True, null=True)),
                ('quantity_unit', models.CharField(blank=True, choices=[('PCS', 'PCS'), ('PACK', 'PACK')], default='PCS', max_length=9, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('weight_unit', models.CharField(blank=True, choices=[('', ''), ('mg', 'mg'), ('g', 'g'), ('kg', 'kg')], default='', max_length=9, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('rack_number', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('category', models.ManyToManyField(blank=True, to='inventory.ProductCategories')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(blank=True, max_length=30, null=True)),
                ('product_name', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('cost', models.FloatField(blank=True, null=True)),
                ('mrp', models.FloatField(blank=True, null=True)),
                ('discount_price', models.FloatField(blank=True, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.product')),
            ],
        ),
    ]
