# Generated by Django 3.1.2 on 2020-10-06 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cost', models.FloatField()),
                ('mrp', models.FloatField()),
                ('discount_price', models.FloatField(blank=True, null=True)),
                ('quantity', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('product_code', models.CharField(max_length=20)),
                ('slug', models.SlugField()),
            ],
        ),
    ]
