# Generated by Django 3.1.2 on 2020-10-20 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity_unit',
            field=models.CharField(blank=True, choices=[('PCS', 'PCS'), ('PACK', 'PACK')], default='PCS', max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='rack_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_unit',
            field=models.CharField(blank=True, choices=[('', ''), ('mg', 'mg'), ('g', 'g'), ('kg', 'kg')], default='', max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
