# Generated by Django 3.1.2 on 2022-02-02 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20210407_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
