# Generated by Django 3.1.2 on 2021-01-03 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupons_discounts', '0001_initial'),
        ('inventory', '0002_auto_20210103_0302'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coupons_discounts.discount'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coupons_discounts.discount'),
        ),
    ]
