# Generated by Django 3.1.2 on 2020-12-24 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20201224_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='mrp',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
