# Generated by Django 3.1.2 on 2020-10-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20201009_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
