# Generated by Django 3.1.2 on 2021-01-03 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20210103_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='weight_unit',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
