# Generated by Django 3.1.2 on 2020-10-09 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20201009_1418'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductCategories',
            new_name='ProductCategory',
        ),
    ]
