# Generated by Django 3.1.2 on 2021-01-26 19:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20210103_0504'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCompanyNew',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'ProductCompany',
            },
        ),
        migrations.CreateModel(
            name='ProductNew',
            fields=[
                ('product_code', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('rack_number', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.productcompanynew')),
                ('category', models.ManyToManyField(blank=True, to='inventory.ProductCategories')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField(blank=True, null=True)),
                ('mrp', models.FloatField(blank=True, null=True)),
                ('discount_price', models.FloatField(blank=True, null=True)),
                ('discount_percentage', models.FloatField(blank=True, null=True)),
                ('quantity_unit', models.CharField(blank=True, choices=[('PCS', 'PCS'), ('PACK', 'PACK')], default='PCS', max_length=9, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('weight_unit', models.CharField(blank=True, choices=[('', ''), ('mg', 'mg'), ('g', 'g'), ('kg', 'kg'), ('ml', 'ml'), ('L', 'L')], default='', max_length=9, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('product_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.productnew')),
            ],
        ),
    ]
