# Generated by Django 3.1.2 on 2022-02-08 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20220202_1831'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariation',
            old_name='photo',
            new_name='image',
        ),
    ]
