# Generated by Django 3.1.2 on 2021-01-31 22:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_productcompanynew_productnew_productvariation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariation',
            old_name='product_code',
            new_name='product',
        ),
        migrations.AddField(
            model_name='productvariation',
            name='modified_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True),
        ),
    ]
