# Generated by Django 3.1.2 on 2023-01-29 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20220405_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='min_mrp',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
