# Generated by Django 3.1.2 on 2020-10-06 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_orderitem_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='price',
            new_name='amount',
        ),
    ]
