# Generated by Django 3.1.2 on 2021-02-04 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0006_auto_20210131_2221'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_ordered', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('complete', models.BooleanField(default=False, null=True)),
                ('bill_cost', models.FloatField(blank=True, null=True)),
                ('bill_mrp', models.FloatField(blank=True, null=True)),
                ('bill_revenue', models.FloatField(blank=True, null=True)),
                ('bill_profit', models.FloatField(blank=True, null=True)),
                ('bill_quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelOptions(
            name='productnew',
            options={'verbose_name_plural': 'ProductsNew'},
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('company', models.ManyToManyField(blank=True, to='inventory.ProductCompany')),
            ],
        ),
        migrations.CreateModel(
            name='StockBillItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('cost', models.FloatField(blank=True, null=True)),
                ('mrp', models.FloatField(blank=True, null=True)),
                ('discount_price', models.FloatField(blank=True, null=True)),
                ('discount_percentage', models.FloatField(blank=True, null=True)),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('quantity_unit', models.CharField(blank=True, choices=[('PCS', 'PCS'), ('PACK', 'PACK')], default='PCS', max_length=9, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('weight_unit', models.CharField(blank=True, choices=[('', ''), ('mg', 'mg'), ('g', 'g'), ('kg', 'kg'), ('ml', 'ml'), ('L', 'L')], default='', max_length=9, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('product_variation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.productvariation')),
                ('stock_bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.stockbill')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.vendor')),
            ],
            options={
                'verbose_name_plural': 'StockBillItems',
            },
        ),
        migrations.AddField(
            model_name='stockbill',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.vendor'),
        ),
    ]
