# Generated by Django 3.1.2 on 2023-02-12 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_product_min_mrp_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='colour',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='orders',
            field=models.IntegerField(default=0),
        ),
    ]
