# Generated by Django 3.1.2 on 2020-11-05 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_remove_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategories',
            name='id',
        ),
        migrations.AlterField(
            model_name='productcategories',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
