# Generated by Django 3.1.2 on 2021-02-04 21:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20210204_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockbill',
            name='date_ordered',
            field=models.DateField(blank=True, default=django.utils.timezone.now, editable=False, null=True),
        ),
    ]
