# Generated by Django 3.1.2 on 2021-02-04 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_auto_20210204_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockbill',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
