# Generated by Django 3.1.2 on 2021-02-04 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_auto_20210204_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockbillitems',
            name='vendor',
        ),
    ]
