# Generated by Django 3.1.2 on 2021-02-06 05:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_remove_stockbillitems_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockbill',
            name='date_ordered',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
