# Generated by Django 3.1.2 on 2021-02-06 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_auto_20210206_0555'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockbillitems',
            name='is_new_variation',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
