# Generated by Django 3.1.2 on 2021-02-06 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_stockbillitems_is_new_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockbillitems',
            name='is_new_variation',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
