# Generated by Django 3.1.2 on 2021-02-07 01:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coupons_discounts', '0001_initial'),
        ('inventory', '0014_auto_20210206_0557'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_order', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('payment_mode', models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Paytm', 'Paytm'), ('UPI', 'UPI'), ('Other', 'Other')], default='Cash', max_length=10, null=True)),
                ('cart_revenue', models.FloatField(blank=True, null=True)),
                ('cart_profit', models.FloatField(blank=True, null=True)),
                ('cart_cost', models.FloatField(blank=True, null=True)),
                ('cart_mrp', models.FloatField(blank=True, null=True)),
                ('cart_quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('complete', models.BooleanField(default=False, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coupons_discounts.discount')),
            ],
            options={
                'verbose_name_plural': 'Orders - New',
            },
        ),
        migrations.CreateModel(
            name='OrderItemNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(blank=True, max_length=30, null=True)),
                ('product_name', models.CharField(blank=True, max_length=100, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('weight_unit', models.CharField(blank=True, max_length=9, null=True)),
                ('cost', models.FloatField(blank=True, null=True)),
                ('mrp', models.FloatField(blank=True, null=True)),
                ('discount_price', models.FloatField(blank=True, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coupons_discounts.discount')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.ordernew')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.productnew')),
                ('variation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.productvariation')),
            ],
            options={
                'verbose_name_plural': 'Order Items - New',
            },
        ),
    ]
