# Generated by Django 3.1.2 on 2020-11-09 16:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_auto_20201105_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='modified_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True),
        ),
    ]
