# Generated by Django 3.1.2 on 2021-02-12 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_orderitemnew_ordernew'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitemnew',
            old_name='product_name',
            new_name='name',
        ),
    ]
