# Generated by Django 3.1.2 on 2021-02-16 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '__first__'),
        ('inventory', '0016_auto_20210212_0504'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordernew',
            name='pos_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.poscustomer'),
        ),
    ]
