# Generated by Django 3.1.2 on 2020-12-19 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_auto_20201109_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='discount_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='mrp',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
