# Generated by Django 3.1.2 on 2021-02-16 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_ordernew_pos_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordernew',
            name='pos_customer',
        ),
    ]
