# Generated by Django 3.1.2 on 2020-12-19 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_auto_20201219_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='cost',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
