# Generated by Django 3.1.2 on 2021-02-16 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_poscustomer'),
        ('inventory', '0018_remove_ordernew_pos_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordernew',
            name='pos_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.poscustomer'),
        ),
    ]
