# Generated by Django 3.1.2 on 2020-12-20 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_orderitem_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
